In [85]:
#Task1.1 - Create a list: nums = [3, 5, 7, 8, 12], make another list named ‘cubes’ and append the cubes of the given list ‘nums’ in this list and print it.

In [3]:
nums = [3,5,7,8,12]

In [13]:
cubes = []

In [15]:
for num in nums:
    cubes.append(num ** 3)

In [17]:
print(cubes)

[27, 125, 343, 512, 1728]


In [87]:
#Task1.2 - Create an empty dictionary: dict = {}, add the following data to the dictionary: ‘parrot’: 2, ‘goat’: 4, ‘spider’: 8, ‘crab’: 10 as key value pairs.

In [23]:
dict = {}

In [25]:
dict['parrot'] = 2

In [27]:
dict['goat'] = 4

In [29]:
dict['spider'] = 8

In [31]:
dict['crab'] = 10

In [33]:
print(dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [89]:
#Task1.3 - Use the ‘items’ method to loop over the dictionary (dict) and print the animals and their corresponding legs. Sum the legs of each animal, and print the total at the end.

In [37]:
total_legs = 0

In [39]:
for animal, legs in dict.items():
    print(f"{animal}: {legs} legs")
    total_legs += legs

parrot: 2 legs
goat: 4 legs
spider: 8 legs
crab: 10 legs


In [41]:
print(f"Total number of legs: {total_legs}")

Total number of legs: 24


In [91]:
#Task1.4 - Create a tuple: A = (3, 9, 4, [5, 6]), change the value in the list from ‘5’ to ‘8’.

In [45]:
A = (3, 9, 4, [5, 6])

In [47]:
A[3][0] = 8

In [49]:
print(A)

(3, 9, 4, [8, 6])


In [93]:
#Task1.5 - Delete the tuple A.

In [53]:
del A

In [95]:
#Task1.6 - Create another tuple: B = (‘a’, ‘p’, ‘p’, ‘l’, ‘e’), print the number of occurrences of ‘p’ in the tuple.

In [57]:
B = ('a', 'p', 'p', 'l', 'e')

In [63]:
count_p = B.count('p')

In [65]:
print(f"The letter 'p' appears {count_p} times in the tuple")

The letter 'p' appears 2 times in the tuple


In [67]:
count_a = B.count('a')

In [69]:
print(f"The letter 'a' appears {count_a} times in the tuple")

The letter 'a' appears 1 times in the tuple


In [97]:
#Task1.7 - Print the index of ‘l’ in the tuple.

In [73]:
B = ('a', 'p', 'p', 'l', 'e')

In [75]:
index_l = B.index('l')

In [77]:
print(f"The index of 'l' in the tuple is: {index_l}")

The index of 'l' in the tuple is: 3


In [79]:
index_e = B.index('e')

In [81]:
print(f"The index of 'e' in the tuple is: {index_e}")

The index of 'e' in the tuple is: 4


In [99]:
#Task2.1 - Convert matrix A into numpy array

In [101]:
import numpy as np

In [103]:
A = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

In [105]:
A_np = np.array(A)

In [107]:
print(A_np)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [109]:
#Task2.2 -  Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2. Store it in b which is a numpy array of shape (2, 2)

In [111]:
B = A_np[:2, :2]

In [113]:
print(B)

[[1 2]
 [5 6]]


In [115]:
#Task2.3 - Create an empty matrix ‘C’ with the same shape as ‘A

In [117]:
C = np.empty_like(A)

In [ ]:
#Task2.4 - 

In [131]:
X = np.array([[1, 2], [3, 4]])

In [146]:
v = np.array([9, 10])

In [148]:
C = np.empty_like(X)

In [150]:
for i in range(X.shape[1]): 
    C[:, i] = X[:, i] + v

In [152]:
print("Matrix C:")

Matrix C:


In [158]:
Y = np.array([[5, 6], [7, 8]])

In [154]:
print(C)

[[10 11]
 [13 14]]


In [170]:
#Task2.5 -  Add and print the matrices X and Y.

In [156]:
X = np.array([[1, 2], [3, 4]])

In [160]:
Z = X + Y

In [164]:
print("Matrix Z (X + Y):")

Matrix Z (X + Y):


In [168]:
print(C)

[[10 11]
 [13 14]]


In [172]:
#Task2.6 - Multiply and print the matrices X and Y.

In [174]:
Z = X @ Y  

In [176]:
print("Matrix Z (X * Y):")

Matrix Z (X * Y):


In [178]:
print(Z)

[[19 22]
 [43 50]]


In [180]:
#Task2.7 -  Compute and print the element wise square root of matrix Y.

In [182]:
Y = np.array([[5, 6], [7, 8]])

In [184]:
sqrt_Y = np.sqrt(Y)

In [186]:
print("Element-wise square root of matrix Y:")

Element-wise square root of matrix Y:


In [188]:
print(sqrt_Y)

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [190]:
#Task2.8 - Compute and print the dot product of the matrix X and vector v.

In [192]:
dot_product = X @ v

In [194]:
print("Dot product of matrix X and vector v:")

Dot product of matrix X and vector v:


In [196]:
print(dot_product)

[29 67]


In [198]:
#Task2.9 - Compute and print the sum of each column of X.

In [200]:
column_sums = np.sum(X, axis=0)

In [202]:
print("Sum of each column of matrix X:")

Sum of each column of matrix X:


In [204]:
print(column_sums)

[4 6]


In [61]:
#Task3.1 - Create a function ‘Compute’ that takes two arguments, distance and time, and use it to calculate velocity

In [111]:
def Compute(distance, time):
    # Check if time is zero to avoid division by zero
    if time == 0:
        return "Time cannot be zero."
    
    velocity = distance / time
    return velocity

distance = 100  
time = 20       

velocity = Compute(distance, time)
print(f"Velocity: {velocity} meters per second")

# Now let's create a pandas DataFrame for distances and times
data = {
    'Distance': [100, 150, 200, 50, 120],  
    'Time': [20, 30, 40, 10, 15]           
}

df = pd.DataFrame(data)

# Calculate velocity for each row and add it as a new column
df['Velocity'] = df.apply(lambda row: Compute(row['Distance'], row['Time']), axis=1)

print(df)

Velocity: 5.0 meters per second
   Distance  Time  Velocity
0       100    20       5.0
1       150    30       5.0
2       200    40       5.0
3        50    10       5.0
4       120    15       8.0


In [115]:
#Task3.2 - Make a list named ‘even_num’ that contains all even numbers up till 12. Create a function ‘mult’ that takes the list‘even_num’ as an argument and calculates the products of all entries using a for loop

In [117]:
even_num = [2, 4, 6, 8, 10, 12]

# Define the function to calculate the product of all elements in the list
def mult(even_num):
    product = 1  
    
    # Loop through each number in the list and multiply it with the current product
    for num in even_num:
        product *= num
    
    return product

# Call the function and print the result
result = mult(even_num)
print(f"The product of all even numbers up to 12 is: {result}")


The product of all even numbers up to 12 is: 46080


In [109]:
#Task4.1 - Print only the first two rows of the dataframe.

In [11]:
import pandas as pd

In [13]:
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

In [15]:
df = pd.DataFrame(data)

In [17]:
print(df.head(2))

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [19]:
#Task4.2 -  Print the second column.

In [21]:
print(df['C2'])

0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [23]:
#Task4.3 -  Change the name of the third column from ‘C3’ to ‘B3’

In [25]:
df.rename(columns={'C3': 'B3'}, inplace=True)

In [27]:
print(df)

   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [29]:
#Task4.4 - Add a new column to the dataframe and name it ‘Sum

In [31]:
df['Sum'] = df.sum(axis=1)

In [33]:
print(df)

   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [35]:
#Task4.5 - Sum the entries of each row and add the result in the column ‘Sum’.

In [43]:
df['Sum'] = df.sum(axis=1)

In [45]:
print(df)


   C1  C2  B3  C4   Sum
0   1   6   7   7  21.0
1   2   7   9   5  23.0
2   3   5   8   2  18.0
3   5   4   6   8  23.0
4   5   8   5   8  26.0


In [47]:
#Task4.6 -  Read CSV file named ‘hello_sample.csv’ (the file is available in the class Google Drive shared folder) into a Pandas dataframe.  

In [3]:
import pandas as pd

In [11]:
dataset = pd.read_csv("hello_sample.csv")

In [ ]:
#Task4.7 -  Print complete dataframe

In [15]:
print(dataset)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [17]:
#Task4.8 -  Print only bottom 2 records of the dataframe.

In [19]:
print(dataset.tail(2))

   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [21]:
#Task4.9 -  Print information about the dataframe.

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [29]:
#Task4.10 - Print shape (rows x columns) of the dataframe

In [27]:
print("Shape of the DataFrame:", dataset.shape)

Shape of the DataFrame: (23, 4)


In [31]:
#Task4.11 -  Sort the data of the dataFrame using column ‘Weight’.

In [33]:
dataset_sorted = dataset.sort_values(by='Weight')

In [37]:
print(dataset_sorted)

    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [39]:
#Task4.12 -  Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.

In [41]:
print("Checking for missing values:")

Checking for missing values:


In [45]:
print(dataset.isnull())

    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [55]:
dataset_cleaned = dataset.dropna()

In [57]:
print("\nDataFrame after dropping rows with missing values:")


DataFrame after dropping rows with missing values:


In [59]:
print(dataset_cleaned)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66
